name: Itch.io Deploy Workflow

on:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
        env:
          CI: true

      - name: Install yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: yarn build
        run: yarn build
        env:
          CI: true

      - name: Deploy
        uses: josephbmanley/butler-publish-itchio-action@v1.0.2
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
          CHANNEL: HTML
          ITCH_GAME: indivisible-slayer
          ITCH_USER: galemius
          PACKAGE: dist
